services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: shade
      POSTGRES_PASSWORD: shade
      POSTGRES_DB: shade
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./scripts/init-db:/docker-entrypoint-initdb.d

volumes:
  db:
